name: t3calendry
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ">=2.19.4 <3.0.0"
dependencies:
    flutter:
        sdk: flutter
    floor: ^1.4.1
    get: ^4.6.5
    flutter_localization: ^0.1.10
    firebase_analytics: ^10.1.5
    cupertino_icons: ^1.0.2
    firebase_core: ^2.7.1
    calendar_view: ^1.0.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
flutter:
    uses-material-design: true
